services:
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    # set to nobody user for compat w/ wp container
    user: '65534:65534'
    ports:
      - 127.0.0.1:6900:8080
    volumes:
      - /home/CHANGE_TO_USERNAME/sites:/data
      - ./filebrowser/config:/config
    environment:
      - FB_BASEURL=/
    restart: unless-stopped

  # kopia server is 6901

  whatsupdocker:
    image: getwud/wud
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 127.0.0.1:6902:3000

  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: watchtower
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   restart: unless-stopped
  #   environment:
  #     - WATCHTOWER_CLEANUP=true

  # dozzle:
  #   image: amir20/dozzle
  #   container_name: dozzle
  #   networks:
  #     - CHANGE_TO_USERNAME
  #   ports:
  #     - 127.0.0.1:6905:8080
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   restart: unless-stopped
