services:
  caddy:
    container_name: coolify-proxy
    image: 'hgdboost/caddy-docker-proxy'
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - CADDY_DOCKER_POLLING_INTERVAL=15
      - CADDY_DOCKER_CADDYFILE_PATH=/dynamic/Caddyfile
      - CADDY_DOCKER_EVENT_THROTTLE_INTERVAL=2s
      - CROWDSEC_API_KEY=${CROWDSEC_API_KEY}
    networks:
      - coolify
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    labels:
      coolify.managed: true
      coolify.proxy: true
      caddy.email: web@boostcreative.com
      # caddy.debug:
      caddy.servers.2_trusted_proxies_strict:
      caddy.0_order: crowdsec first
      # caddy.1_order: appsec after crowdsec
      caddy.servers.1_trusted_proxies: combine
      caddy.servers.1_trusted_proxies.cloudflare:
      caddy.servers.1_trusted_proxies.static: private_ranges
      caddy.servers.client_ip_headers: Cf-Connecting-Ip
      caddy.crowdsec.0_api_url: http://crowdsec:8080
      caddy.crowdsec.1_api_key: '{$$CROWDSEC_API_KEY}'
      caddy.crowdsec.2_ticker_interval: 15s
      # caddy.crowdsec.2_appsec_url: http://crowdsec:7422
      caddy_0: (crowdsec)
      caddy_0.0_crowdsec:
      # caddy_0.1_appsec:
      caddy_0.log.output: file /var/log/caddy/access.log
      caddy_0.log.output.roll_size: 10MB
      caddy_0.log.output.roll_keep: 5
      caddy_0.log.output.roll_keep_days: 14
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/data/coolify/proxy/caddy/dynamic:/dynamic'
      - '/data/coolify/proxy/caddy/config:/config'
      - '/data/coolify/proxy/caddy/data:/data'
      - caddy-logs:/var/log/caddy

  crowdsec:
    image: docker.io/crowdsecurity/crowdsec:latest
    container_name: crowdsec
    environment:
      # - DEBUG=true
      - TZ=America/Detroit
      - USE_WAL=true
      - GID=1000
      - COLLECTIONS=crowdsecurity/caddy crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/wordpress
      - BOUNCER_KEY_CADDY=${CROWDSEC_API_KEY}
    volumes:
      - crowdsec-db:/var/lib/crowdsec/data/
      - caddy-logs:/var/log/caddy:ro
      - /etc/coolify-setup/proxy/acquis.yaml:/etc/crowdsec/acquis.yaml
    networks:
      - coolify
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true

networks:
  coolify:
    external: true
volumes:
  crowdsec-db:
  caddy-logs:
